### ISSUE TITLE
Number of tickets decreases over $10k

### ISSUE THREAD

**Issue by codingmatty** [sjoseph7/yotta-odds-eAPR#1]
The official rules state:

> Have Funds on Deposit with Yotta App. For every $25 you have on deposit up to $10,000, you will receive one (1) Ticket. For every $150 above $10,000, you will receive one (1) ticket.

This means $20k deposit would only yield 466 tickets, not 800.

I assume this may have changed since this calculator was implemented.

**Comment by sjoseph7** [comment]
Thanks for submitting the issue - I've updated the calculator accordingly. Let me know if you run into any other issues!
